    1: import numpy.exceptions as ex
    2: 
    3: ex.AxisError("test")
    4: ex.AxisError(1, ndim=2)
    5: ex.AxisError(1, ndim=2, msg_prefix="error")
    6: ex.AxisError(1, ndim=2, msg_prefix=None)
